// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file provider/v1/update_provider_models.proto (package provider.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file provider/v1/update_provider_models.proto.
 */
export const file_provider_v1_update_provider_models: GenFile = /*@__PURE__*/
  fileDesc("Cihwcm92aWRlci92MS91cGRhdGVfcHJvdmlkZXJfbW9kZWxzLnByb3RvEgtwcm92aWRlci52MSI0ChtVcGRhdGVQcm92aWRlck1vZGVsc1JlcXVlc3QSFQoNcHJvdmlkZXJfbmFtZRgBIAEoCSIeChxVcGRhdGVQcm92aWRlck1vZGVsc1Jlc3BvbnNlQqUBCg9jb20ucHJvdmlkZXIudjFCGVVwZGF0ZVByb3ZpZGVyTW9kZWxzUHJvdG9QAVoqYXJ1a2FiZS9nZW4vY29ubmVjdC9wcm92aWRlci92MTtwcm92aWRlcnYxogIDUFhYqgILUHJvdmlkZXIuVjHKAgtQcm92aWRlclxWMeICF1Byb3ZpZGVyXFYxXEdQQk1ldGFkYXRh6gIMUHJvdmlkZXI6OlYxYgZwcm90bzM");

/**
 * @generated from message provider.v1.UpdateProviderModelsRequest
 */
export type UpdateProviderModelsRequest = Message<"provider.v1.UpdateProviderModelsRequest"> & {
  /**
   * @generated from field: string provider_name = 1;
   */
  providerName: string;
};

/**
 * Describes the message provider.v1.UpdateProviderModelsRequest.
 * Use `create(UpdateProviderModelsRequestSchema)` to create a new message.
 */
export const UpdateProviderModelsRequestSchema: GenMessage<UpdateProviderModelsRequest> = /*@__PURE__*/
  messageDesc(file_provider_v1_update_provider_models, 0);

/**
 * @generated from message provider.v1.UpdateProviderModelsResponse
 */
export type UpdateProviderModelsResponse = Message<"provider.v1.UpdateProviderModelsResponse"> & {
};

/**
 * Describes the message provider.v1.UpdateProviderModelsResponse.
 * Use `create(UpdateProviderModelsResponseSchema)` to create a new message.
 */
export const UpdateProviderModelsResponseSchema: GenMessage<UpdateProviderModelsResponse> = /*@__PURE__*/
  messageDesc(file_provider_v1_update_provider_models, 1);

