// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file models/v1/common.proto (package models.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file models/v1/common.proto.
 */
export const file_models_v1_common: GenFile = /*@__PURE__*/
  fileDesc("ChZtb2RlbHMvdjEvY29tbW9uLnByb3RvEgltb2RlbHMudjEiMAoRUGFnaW5hdGlvblJlcXVlc3QSDAoEcGFnZRgBIAEoDRINCgVsaW1pdBgCIAEoDSJ7Cg5QYWdpbmF0aW9uRGF0YRIMCgRwYWdlGAEgASgNEg0KBWxpbWl0GAIgASgNEhMKC3RvdGFsX2l0ZW1zGAMgASgNEhMKC3RvdGFsX3BhZ2VzGAQgASgNEhAKCGhhc19uZXh0GAUgASgIEhAKCGhhc19wcmV2GAYgASgIIvQBCghUaW1lRGF0YRIuCgpjcmVhdGVkX2F0GAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBI0CgthcmNoaXZlZF9hdBgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIAIgBARIzCgpkZWxldGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgBiAEBQg4KDF9hcmNoaXZlZF9hdEINCgtfZGVsZXRlZF9hdEKJAQoNY29tLm1vZGVscy52MUILQ29tbW9uUHJvdG9QAVomYXJ1a2FiZS9nZW4vY29ubmVjdC9tb2RlbHMvdjE7bW9kZWxzdjGiAgNNWFiqAglNb2RlbHMuVjHKAglNb2RlbHNcVjHiAhVNb2RlbHNcVjFcR1BCTWV0YWRhdGHqAgpNb2RlbHM6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * @generated from message models.v1.PaginationRequest
 */
export type PaginationRequest = Message<"models.v1.PaginationRequest"> & {
  /**
   * @generated from field: uint32 page = 1;
   */
  page: number;

  /**
   * @generated from field: uint32 limit = 2;
   */
  limit: number;
};

/**
 * Describes the message models.v1.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
export const PaginationRequestSchema: GenMessage<PaginationRequest> = /*@__PURE__*/
  messageDesc(file_models_v1_common, 0);

/**
 * @generated from message models.v1.PaginationData
 */
export type PaginationData = Message<"models.v1.PaginationData"> & {
  /**
   * @generated from field: uint32 page = 1;
   */
  page: number;

  /**
   * @generated from field: uint32 limit = 2;
   */
  limit: number;

  /**
   * @generated from field: uint32 total_items = 3;
   */
  totalItems: number;

  /**
   * @generated from field: uint32 total_pages = 4;
   */
  totalPages: number;

  /**
   * @generated from field: bool has_next = 5;
   */
  hasNext: boolean;

  /**
   * @generated from field: bool has_prev = 6;
   */
  hasPrev: boolean;
};

/**
 * Describes the message models.v1.PaginationData.
 * Use `create(PaginationDataSchema)` to create a new message.
 */
export const PaginationDataSchema: GenMessage<PaginationData> = /*@__PURE__*/
  messageDesc(file_models_v1_common, 1);

/**
 * @generated from message models.v1.TimeData
 */
export type TimeData = Message<"models.v1.TimeData"> & {
  /**
   * @generated from field: google.protobuf.Timestamp created_at = 1;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 2;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp archived_at = 3;
   */
  archivedAt?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp deleted_at = 4;
   */
  deletedAt?: Timestamp;
};

/**
 * Describes the message models.v1.TimeData.
 * Use `create(TimeDataSchema)` to create a new message.
 */
export const TimeDataSchema: GenMessage<TimeData> = /*@__PURE__*/
  messageDesc(file_models_v1_common, 2);

