// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file models/v1/message.proto (package models.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { MessageContent } from "./message_content_pb";
import { file_models_v1_message_content } from "./message_content_pb";
import type { Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file models/v1/message.proto.
 */
export const file_models_v1_message: GenFile = /*@__PURE__*/
  fileDesc("Chdtb2RlbHMvdjEvbWVzc2FnZS5wcm90bxIJbW9kZWxzLnYxIpcBCgdNZXNzYWdlEgoKAmlkGAEgASgJEiQKBHJvbGUYAiABKA4yFi5tb2RlbHMudjEuTWVzc2FnZVJvbGUSKgoHY29udGVudBgDIAMoCzIZLm1vZGVscy52MS5NZXNzYWdlQ29udGVudBIuCgpjcmVhdGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCpeCgtNZXNzYWdlUm9sZRIcChhNRVNTQUdFX1JPTEVfVU5TUEVDSUZJRUQQABIVChFNRVNTQUdFX1JPTEVfVVNFUhABEhoKFk1FU1NBR0VfUk9MRV9BU1NJU1RBTlQQAkKKAQoNY29tLm1vZGVscy52MUIMTWVzc2FnZVByb3RvUAFaJmFydWthYmUvZ2VuL2Nvbm5lY3QvbW9kZWxzL3YxO21vZGVsc3YxogIDTVhYqgIJTW9kZWxzLlYxygIJTW9kZWxzXFYx4gIVTW9kZWxzXFYxXEdQQk1ldGFkYXRh6gIKTW9kZWxzOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp, file_models_v1_message_content]);

/**
 * @generated from message models.v1.Message
 */
export type Message = Message$1<"models.v1.Message"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: models.v1.MessageRole role = 2;
   */
  role: MessageRole;

  /**
   * @generated from field: repeated models.v1.MessageContent content = 3;
   */
  content: MessageContent[];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message models.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema: GenMessage<Message> = /*@__PURE__*/
  messageDesc(file_models_v1_message, 0);

/**
 * @generated from enum models.v1.MessageRole
 */
export enum MessageRole {
  /**
   * @generated from enum value: MESSAGE_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MESSAGE_ROLE_USER = 1;
   */
  USER = 1,

  /**
   * @generated from enum value: MESSAGE_ROLE_ASSISTANT = 2;
   */
  ASSISTANT = 2,
}

/**
 * Describes the enum models.v1.MessageRole.
 */
export const MessageRoleSchema: GenEnum<MessageRole> = /*@__PURE__*/
  enumDesc(file_models_v1_message, 0);

