// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file models/v1/model.proto (package models.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file models/v1/model.proto.
 */
export const file_models_v1_model: GenFile = /*@__PURE__*/
  fileDesc("ChVtb2RlbHMvdjEvbW9kZWwucHJvdG8SCW1vZGVscy52MSKTAQoFTW9kZWwSCgoCaWQYASABKAkSGAoQbW9kZWxfaWRlbnRpZmllchgCIAEoCRIMCgRuYW1lGAMgASgJEi4KCmNyZWF0ZWRfYXQYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEiYKBnN0YXR1cxgFIAEoDjIWLm1vZGVscy52MS5Nb2RlbFN0YXR1cyp8CgtNb2RlbFN0YXR1cxIcChhNT0RFTF9TVEFUVVNfVU5TUEVDSUZJRUQQABIXChNNT0RFTF9TVEFUVVNfQUNUSVZFEAESGQoVTU9ERUxfU1RBVFVTX0lOQUNUSVZFEAISGwoXTU9ERUxfU1RBVFVTX0RFUFJFQ0FURUQQA0KOAQoNY29tLm1vZGVscy52MUIKTW9kZWxQcm90b1ABWixhcnVrYWJlL2dlbi9jb25uZWN0L2FydWthL21vZGVscy92MTttb2RlbHN2MaICA01YWKoCCU1vZGVscy5WMcoCCU1vZGVsc1xWMeICFU1vZGVsc1xWMVxHUEJNZXRhZGF0YeoCCk1vZGVsczo6VjFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message models.v1.Model
 */
export type Model = Message<"models.v1.Model"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string model_identifier = 2;
   */
  modelIdentifier: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: models.v1.ModelStatus status = 5;
   */
  status: ModelStatus;
};

/**
 * Describes the message models.v1.Model.
 * Use `create(ModelSchema)` to create a new message.
 */
export const ModelSchema: GenMessage<Model> = /*@__PURE__*/
  messageDesc(file_models_v1_model, 0);

/**
 * @generated from enum models.v1.ModelStatus
 */
export enum ModelStatus {
  /**
   * @generated from enum value: MODEL_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Available to work with
   *
   * @generated from enum value: MODEL_STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * Not available for UI
   *
   * @generated from enum value: MODEL_STATUS_INACTIVE = 2;
   */
  INACTIVE = 2,

  /**
   * Deprecated by provider
   *
   * @generated from enum value: MODEL_STATUS_DEPRECATED = 3;
   */
  DEPRECATED = 3,
}

/**
 * Describes the enum models.v1.ModelStatus.
 */
export const ModelStatusSchema: GenEnum<ModelStatus> = /*@__PURE__*/
  enumDesc(file_models_v1_model, 0);

