// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file chat/v1/auto_chat_title_update.proto (package chat.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chat/v1/auto_chat_title_update.proto.
 */
export const file_chat_v1_auto_chat_title_update: GenFile = /*@__PURE__*/
  fileDesc("CiRjaGF0L3YxL2F1dG9fY2hhdF90aXRsZV91cGRhdGUucHJvdG8SB2NoYXQudjEiLQoaQXV0b0NoYXRUaXRsZVVwZGF0ZVJlcXVlc3QSDwoHY2hhdF9pZBgBIAEoCSIsChtBdXRvQ2hhdFRpdGxlVXBkYXRlUmVzcG9uc2USDQoFdGl0bGUYASABKAlCjgEKC2NvbS5jaGF0LnYxQhhBdXRvQ2hhdFRpdGxlVXBkYXRlUHJvdG9QAVooYXJ1a2FiZS9nZW4vY29ubmVjdC9hcnVrYS9jaGF0L3YxO2NoYXR2MaICA0NYWKoCB0NoYXQuVjHKAgdDaGF0XFYx4gITQ2hhdFxWMVxHUEJNZXRhZGF0YeoCCENoYXQ6OlYxYgZwcm90bzM");

/**
 * @generated from message chat.v1.AutoChatTitleUpdateRequest
 */
export type AutoChatTitleUpdateRequest = Message<"chat.v1.AutoChatTitleUpdateRequest"> & {
  /**
   * @generated from field: string chat_id = 1;
   */
  chatId: string;
};

/**
 * Describes the message chat.v1.AutoChatTitleUpdateRequest.
 * Use `create(AutoChatTitleUpdateRequestSchema)` to create a new message.
 */
export const AutoChatTitleUpdateRequestSchema: GenMessage<AutoChatTitleUpdateRequest> = /*@__PURE__*/
  messageDesc(file_chat_v1_auto_chat_title_update, 0);

/**
 * @generated from message chat.v1.AutoChatTitleUpdateResponse
 */
export type AutoChatTitleUpdateResponse = Message<"chat.v1.AutoChatTitleUpdateResponse"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;
};

/**
 * Describes the message chat.v1.AutoChatTitleUpdateResponse.
 * Use `create(AutoChatTitleUpdateResponseSchema)` to create a new message.
 */
export const AutoChatTitleUpdateResponseSchema: GenMessage<AutoChatTitleUpdateResponse> = /*@__PURE__*/
  messageDesc(file_chat_v1_auto_chat_title_update, 1);

