// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file chat/v1/chat_messages.proto (package chat.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message as Message$1 } from "../../models/v1/message_pb";
import { file_models_v1_message } from "../../models/v1/message_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chat/v1/chat_messages.proto.
 */
export const file_chat_v1_chat_messages: GenFile = /*@__PURE__*/
  fileDesc("ChtjaGF0L3YxL2NoYXRfbWVzc2FnZXMucHJvdG8SB2NoYXQudjEiJgoTQ2hhdE1lc3NhZ2VzUmVxdWVzdBIPCgdjaGF0X2lkGAEgASgJIjwKFENoYXRNZXNzYWdlc1Jlc3BvbnNlEiQKCG1lc3NhZ2VzGAEgAygLMhIubW9kZWxzLnYxLk1lc3NhZ2VChwEKC2NvbS5jaGF0LnYxQhFDaGF0TWVzc2FnZXNQcm90b1ABWihhcnVrYWJlL2dlbi9jb25uZWN0L2FydWthL2NoYXQvdjE7Y2hhdHYxogIDQ1hYqgIHQ2hhdC5WMcoCB0NoYXRcVjHiAhNDaGF0XFYxXEdQQk1ldGFkYXRh6gIIQ2hhdDo6VjFiBnByb3RvMw", [file_models_v1_message]);

/**
 * @generated from message chat.v1.ChatMessagesRequest
 */
export type ChatMessagesRequest = Message<"chat.v1.ChatMessagesRequest"> & {
  /**
   * @generated from field: string chat_id = 1;
   */
  chatId: string;
};

/**
 * Describes the message chat.v1.ChatMessagesRequest.
 * Use `create(ChatMessagesRequestSchema)` to create a new message.
 */
export const ChatMessagesRequestSchema: GenMessage<ChatMessagesRequest> = /*@__PURE__*/
  messageDesc(file_chat_v1_chat_messages, 0);

/**
 * @generated from message chat.v1.ChatMessagesResponse
 */
export type ChatMessagesResponse = Message<"chat.v1.ChatMessagesResponse"> & {
  /**
   * @generated from field: repeated models.v1.Message messages = 1;
   */
  messages: Message$1[];
};

/**
 * Describes the message chat.v1.ChatMessagesResponse.
 * Use `create(ChatMessagesResponseSchema)` to create a new message.
 */
export const ChatMessagesResponseSchema: GenMessage<ChatMessagesResponse> = /*@__PURE__*/
  messageDesc(file_chat_v1_chat_messages, 1);

