// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file chat/v1/delete_chat.proto (package chat.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chat/v1/delete_chat.proto.
 */
export const file_chat_v1_delete_chat: GenFile = /*@__PURE__*/
  fileDesc("ChljaGF0L3YxL2RlbGV0ZV9jaGF0LnByb3RvEgdjaGF0LnYxIiQKEURlbGV0ZUNoYXRSZXF1ZXN0Eg8KB2NoYXRfaWQYASABKAkiFAoSRGVsZXRlQ2hhdFJlc3BvbnNlQoUBCgtjb20uY2hhdC52MUIPRGVsZXRlQ2hhdFByb3RvUAFaKGFydWthYmUvZ2VuL2Nvbm5lY3QvYXJ1a2EvY2hhdC92MTtjaGF0djGiAgNDWFiqAgdDaGF0LlYxygIHQ2hhdFxWMeICE0NoYXRcVjFcR1BCTWV0YWRhdGHqAghDaGF0OjpWMWIGcHJvdG8z");

/**
 * @generated from message chat.v1.DeleteChatRequest
 */
export type DeleteChatRequest = Message<"chat.v1.DeleteChatRequest"> & {
  /**
   * @generated from field: string chat_id = 1;
   */
  chatId: string;
};

/**
 * Describes the message chat.v1.DeleteChatRequest.
 * Use `create(DeleteChatRequestSchema)` to create a new message.
 */
export const DeleteChatRequestSchema: GenMessage<DeleteChatRequest> = /*@__PURE__*/
  messageDesc(file_chat_v1_delete_chat, 0);

/**
 * @generated from message chat.v1.DeleteChatResponse
 */
export type DeleteChatResponse = Message<"chat.v1.DeleteChatResponse"> & {
};

/**
 * Describes the message chat.v1.DeleteChatResponse.
 * Use `create(DeleteChatResponseSchema)` to create a new message.
 */
export const DeleteChatResponseSchema: GenMessage<DeleteChatResponse> = /*@__PURE__*/
  messageDesc(file_chat_v1_delete_chat, 1);

