// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file chat/v1/edit_chat.proto (package chat.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Chat } from "../../models/v1/chat_pb";
import { file_models_v1_chat } from "../../models/v1/chat_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chat/v1/edit_chat.proto.
 */
export const file_chat_v1_edit_chat: GenFile = /*@__PURE__*/
  fileDesc("ChdjaGF0L3YxL2VkaXRfY2hhdC5wcm90bxIHY2hhdC52MSKRAQoPRWRpdENoYXRSZXF1ZXN0EhQKB2NoYXRfaWQYASABKAlIAIgBARISCgV0aXRsZRgCIAEoCUgBiAEBEhMKBnByb21wdBgDIAEoCUgCiAEBEhMKBnBpbm5lZBgEIAEoCEgDiAEBQgoKCF9jaGF0X2lkQggKBl90aXRsZUIJCgdfcHJvbXB0QgkKB19waW5uZWQiMQoQRWRpdENoYXRSZXNwb25zZRIdCgRjaGF0GAEgASgLMg8ubW9kZWxzLnYxLkNoYXRCfQoLY29tLmNoYXQudjFCDUVkaXRDaGF0UHJvdG9QAVoiYXJ1a2FiZS9nZW4vY29ubmVjdC9jaGF0L3YxO2NoYXR2MaICA0NYWKoCB0NoYXQuVjHKAgdDaGF0XFYx4gITQ2hhdFxWMVxHUEJNZXRhZGF0YeoCCENoYXQ6OlYxYgZwcm90bzM", [file_models_v1_chat]);

/**
 * @generated from message chat.v1.EditChatRequest
 */
export type EditChatRequest = Message<"chat.v1.EditChatRequest"> & {
  /**
   * Optional for better validation
   *
   * @generated from field: optional string chat_id = 1;
   */
  chatId?: string;

  /**
   * @generated from field: optional string title = 2;
   */
  title?: string;

  /**
   * @generated from field: optional string prompt = 3;
   */
  prompt?: string;

  /**
   * @generated from field: optional bool pinned = 4;
   */
  pinned?: boolean;
};

/**
 * Describes the message chat.v1.EditChatRequest.
 * Use `create(EditChatRequestSchema)` to create a new message.
 */
export const EditChatRequestSchema: GenMessage<EditChatRequest> = /*@__PURE__*/
  messageDesc(file_chat_v1_edit_chat, 0);

/**
 * @generated from message chat.v1.EditChatResponse
 */
export type EditChatResponse = Message<"chat.v1.EditChatResponse"> & {
  /**
   * @generated from field: models.v1.Chat chat = 1;
   */
  chat?: Chat;
};

/**
 * Describes the message chat.v1.EditChatResponse.
 * Use `create(EditChatResponseSchema)` to create a new message.
 */
export const EditChatResponseSchema: GenMessage<EditChatResponse> = /*@__PURE__*/
  messageDesc(file_chat_v1_edit_chat, 1);

