// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file chat/v1/list_chats.proto (package chat.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Chat } from "../../models/v1/chat_pb";
import { file_models_v1_chat } from "../../models/v1/chat_pb";
import type { PaginationData, PaginationRequest } from "../../models/v1/common_pb";
import { file_models_v1_common } from "../../models/v1/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chat/v1/list_chats.proto.
 */
export const file_chat_v1_list_chats: GenFile = /*@__PURE__*/
  fileDesc("ChhjaGF0L3YxL2xpc3RfY2hhdHMucHJvdG8SB2NoYXQudjEiRAoQTGlzdENoYXRzUmVxdWVzdBIwCgpwYWdpbmF0aW9uGAEgASgLMhwubW9kZWxzLnYxLlBhZ2luYXRpb25SZXF1ZXN0ImIKEUxpc3RDaGF0c1Jlc3BvbnNlEh4KBWNoYXRzGAEgAygLMg8ubW9kZWxzLnYxLkNoYXQSLQoKcGFnaW5hdGlvbhgCIAEoCzIZLm1vZGVscy52MS5QYWdpbmF0aW9uRGF0YUJ+Cgtjb20uY2hhdC52MUIOTGlzdENoYXRzUHJvdG9QAVoiYXJ1a2FiZS9nZW4vY29ubmVjdC9jaGF0L3YxO2NoYXR2MaICA0NYWKoCB0NoYXQuVjHKAgdDaGF0XFYx4gITQ2hhdFxWMVxHUEJNZXRhZGF0YeoCCENoYXQ6OlYxYgZwcm90bzM", [file_models_v1_chat, file_models_v1_common]);

/**
 * @generated from message chat.v1.ListChatsRequest
 */
export type ListChatsRequest = Message<"chat.v1.ListChatsRequest"> & {
  /**
   * @generated from field: models.v1.PaginationRequest pagination = 1;
   */
  pagination?: PaginationRequest;
};

/**
 * Describes the message chat.v1.ListChatsRequest.
 * Use `create(ListChatsRequestSchema)` to create a new message.
 */
export const ListChatsRequestSchema: GenMessage<ListChatsRequest> = /*@__PURE__*/
  messageDesc(file_chat_v1_list_chats, 0);

/**
 * @generated from message chat.v1.ListChatsResponse
 */
export type ListChatsResponse = Message<"chat.v1.ListChatsResponse"> & {
  /**
   * @generated from field: repeated models.v1.Chat chats = 1;
   */
  chats: Chat[];

  /**
   * @generated from field: models.v1.PaginationData pagination = 2;
   */
  pagination?: PaginationData;
};

/**
 * Describes the message chat.v1.ListChatsResponse.
 * Use `create(ListChatsResponseSchema)` to create a new message.
 */
export const ListChatsResponseSchema: GenMessage<ListChatsResponse> = /*@__PURE__*/
  messageDesc(file_chat_v1_list_chats, 1);

