// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file chat/v1/new_chat.proto (package chat.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Chat } from "../../models/v1/chat_pb";
import { file_models_v1_chat } from "../../models/v1/chat_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chat/v1/new_chat.proto.
 */
export const file_chat_v1_new_chat: GenFile = /*@__PURE__*/
  fileDesc("ChZjaGF0L3YxL25ld19jaGF0LnByb3RvEgdjaGF0LnYxIjIKDk5ld0NoYXRSZXF1ZXN0EhAKCG1vZGVsX2lkGAEgASgJEg4KBnByb21wdBgCIAEoCSIwCg9OZXdDaGF0UmVzcG9uc2USHQoEY2hhdBgBIAEoCzIPLm1vZGVscy52MS5DaGF0QnwKC2NvbS5jaGF0LnYxQgxOZXdDaGF0UHJvdG9QAVoiYXJ1a2FiZS9nZW4vY29ubmVjdC9jaGF0L3YxO2NoYXR2MaICA0NYWKoCB0NoYXQuVjHKAgdDaGF0XFYx4gITQ2hhdFxWMVxHUEJNZXRhZGF0YeoCCENoYXQ6OlYxYgZwcm90bzM", [file_models_v1_chat]);

/**
 * @generated from message chat.v1.NewChatRequest
 */
export type NewChatRequest = Message<"chat.v1.NewChatRequest"> & {
  /**
   * @generated from field: string model_id = 1;
   */
  modelId: string;

  /**
   * @generated from field: string prompt = 2;
   */
  prompt: string;
};

/**
 * Describes the message chat.v1.NewChatRequest.
 * Use `create(NewChatRequestSchema)` to create a new message.
 */
export const NewChatRequestSchema: GenMessage<NewChatRequest> = /*@__PURE__*/
  messageDesc(file_chat_v1_new_chat, 0);

/**
 * @generated from message chat.v1.NewChatResponse
 */
export type NewChatResponse = Message<"chat.v1.NewChatResponse"> & {
  /**
   * @generated from field: models.v1.Chat chat = 1;
   */
  chat?: Chat;
};

/**
 * Describes the message chat.v1.NewChatResponse.
 * Use `create(NewChatResponseSchema)` to create a new message.
 */
export const NewChatResponseSchema: GenMessage<NewChatResponse> = /*@__PURE__*/
  messageDesc(file_chat_v1_new_chat, 1);

