// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file chat/v1/services.proto (package chat.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { AutoChatTitleUpdateRequestSchema, AutoChatTitleUpdateResponseSchema } from "./auto_chat_title_update_pb";
import { file_chat_v1_auto_chat_title_update } from "./auto_chat_title_update_pb";
import type { ChatMessageRequestSchema, ChatMessageResponseSchema } from "./chat_message_pb";
import { file_chat_v1_chat_message } from "./chat_message_pb";
import type { ChatMessagesRequestSchema, ChatMessagesResponseSchema } from "./chat_messages_pb";
import { file_chat_v1_chat_messages } from "./chat_messages_pb";
import type { DeleteChatRequestSchema, DeleteChatResponseSchema } from "./delete_chat_pb";
import { file_chat_v1_delete_chat } from "./delete_chat_pb";
import type { EditChatRequestSchema, EditChatResponseSchema } from "./edit_chat_pb";
import { file_chat_v1_edit_chat } from "./edit_chat_pb";
import type { ListChatsRequestSchema, ListChatsResponseSchema } from "./list_chats_pb";
import { file_chat_v1_list_chats } from "./list_chats_pb";
import type { NewChatRequestSchema, NewChatResponseSchema } from "./new_chat_pb";
import { file_chat_v1_new_chat } from "./new_chat_pb";

/**
 * Describes the file chat/v1/services.proto.
 */
export const file_chat_v1_services: GenFile = /*@__PURE__*/
  fileDesc("ChZjaGF0L3YxL3NlcnZpY2VzLnByb3RvEgdjaGF0LnYxMpIECgtDaGF0U2VydmljZRJCCglMaXN0Q2hhdHMSGS5jaGF0LnYxLkxpc3RDaGF0c1JlcXVlc3QaGi5jaGF0LnYxLkxpc3RDaGF0c1Jlc3BvbnNlEjwKB05ld0NoYXQSFy5jaGF0LnYxLk5ld0NoYXRSZXF1ZXN0GhguY2hhdC52MS5OZXdDaGF0UmVzcG9uc2USPwoIRWRpdENoYXQSGC5jaGF0LnYxLkVkaXRDaGF0UmVxdWVzdBoZLmNoYXQudjEuRWRpdENoYXRSZXNwb25zZRJFCgpEZWxldGVDaGF0EhouY2hhdC52MS5EZWxldGVDaGF0UmVxdWVzdBobLmNoYXQudjEuRGVsZXRlQ2hhdFJlc3BvbnNlEksKDENoYXRNZXNzYWdlcxIcLmNoYXQudjEuQ2hhdE1lc3NhZ2VzUmVxdWVzdBodLmNoYXQudjEuQ2hhdE1lc3NhZ2VzUmVzcG9uc2USSgoLQ2hhdE1lc3NhZ2USGy5jaGF0LnYxLkNoYXRNZXNzYWdlUmVxdWVzdBocLmNoYXQudjEuQ2hhdE1lc3NhZ2VSZXNwb25zZTABEmAKE0F1dG9DaGF0VGl0bGVVcGRhdGUSIy5jaGF0LnYxLkF1dG9DaGF0VGl0bGVVcGRhdGVSZXF1ZXN0GiQuY2hhdC52MS5BdXRvQ2hhdFRpdGxlVXBkYXRlUmVzcG9uc2VCgwEKC2NvbS5jaGF0LnYxQg1TZXJ2aWNlc1Byb3RvUAFaKGFydWthYmUvZ2VuL2Nvbm5lY3QvYXJ1a2EvY2hhdC92MTtjaGF0djGiAgNDWFiqAgdDaGF0LlYxygIHQ2hhdFxWMeICE0NoYXRcVjFcR1BCTWV0YWRhdGHqAghDaGF0OjpWMWIGcHJvdG8z", [file_chat_v1_auto_chat_title_update, file_chat_v1_chat_message, file_chat_v1_chat_messages, file_chat_v1_delete_chat, file_chat_v1_edit_chat, file_chat_v1_list_chats, file_chat_v1_new_chat]);

/**
 * @generated from service chat.v1.ChatService
 */
export const ChatService: GenService<{
  /**
   * @generated from rpc chat.v1.ChatService.ListChats
   */
  listChats: {
    methodKind: "unary";
    input: typeof ListChatsRequestSchema;
    output: typeof ListChatsResponseSchema;
  },
  /**
   * @generated from rpc chat.v1.ChatService.NewChat
   */
  newChat: {
    methodKind: "unary";
    input: typeof NewChatRequestSchema;
    output: typeof NewChatResponseSchema;
  },
  /**
   * @generated from rpc chat.v1.ChatService.EditChat
   */
  editChat: {
    methodKind: "unary";
    input: typeof EditChatRequestSchema;
    output: typeof EditChatResponseSchema;
  },
  /**
   * @generated from rpc chat.v1.ChatService.DeleteChat
   */
  deleteChat: {
    methodKind: "unary";
    input: typeof DeleteChatRequestSchema;
    output: typeof DeleteChatResponseSchema;
  },
  /**
   * @generated from rpc chat.v1.ChatService.ChatMessages
   */
  chatMessages: {
    methodKind: "unary";
    input: typeof ChatMessagesRequestSchema;
    output: typeof ChatMessagesResponseSchema;
  },
  /**
   * @generated from rpc chat.v1.ChatService.ChatMessage
   */
  chatMessage: {
    methodKind: "server_streaming";
    input: typeof ChatMessageRequestSchema;
    output: typeof ChatMessageResponseSchema;
  },
  /**
   * @generated from rpc chat.v1.ChatService.AutoChatTitleUpdate
   */
  autoChatTitleUpdate: {
    methodKind: "unary";
    input: typeof AutoChatTitleUpdateRequestSchema;
    output: typeof AutoChatTitleUpdateResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_chat_v1_services, 0);

