// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file chat/v1/services.proto (package chat.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { ChatMessageRequestSchema, ChatMessageResponseSchema } from "./chat_message_pb";
import { file_chat_v1_chat_message } from "./chat_message_pb";
import type { ChatMessagesRequestSchema, ChatMessagesResponseSchema } from "./chat_messages_pb";
import { file_chat_v1_chat_messages } from "./chat_messages_pb";
import type { EditChatRequestSchema, EditChatResponseSchema } from "./edit_chat_pb";
import { file_chat_v1_edit_chat } from "./edit_chat_pb";
import type { ListChatsRequestSchema, ListChatsResponseSchema } from "./list_chats_pb";
import { file_chat_v1_list_chats } from "./list_chats_pb";
import type { NewChatRequestSchema, NewChatResponseSchema } from "./new_chat_pb";
import { file_chat_v1_new_chat } from "./new_chat_pb";

/**
 * Describes the file chat/v1/services.proto.
 */
export const file_chat_v1_services: GenFile = /*@__PURE__*/
  fileDesc("ChZjaGF0L3YxL3NlcnZpY2VzLnByb3RvEgdjaGF0LnYxMukCCgtDaGF0U2VydmljZRJCCglMaXN0Q2hhdHMSGS5jaGF0LnYxLkxpc3RDaGF0c1JlcXVlc3QaGi5jaGF0LnYxLkxpc3RDaGF0c1Jlc3BvbnNlEjwKB05ld0NoYXQSFy5jaGF0LnYxLk5ld0NoYXRSZXF1ZXN0GhguY2hhdC52MS5OZXdDaGF0UmVzcG9uc2USPwoIRWRpdENoYXQSGC5jaGF0LnYxLkVkaXRDaGF0UmVxdWVzdBoZLmNoYXQudjEuRWRpdENoYXRSZXNwb25zZRJLCgxDaGF0TWVzc2FnZXMSHC5jaGF0LnYxLkNoYXRNZXNzYWdlc1JlcXVlc3QaHS5jaGF0LnYxLkNoYXRNZXNzYWdlc1Jlc3BvbnNlEkoKC0NoYXRNZXNzYWdlEhsuY2hhdC52MS5DaGF0TWVzc2FnZVJlcXVlc3QaHC5jaGF0LnYxLkNoYXRNZXNzYWdlUmVzcG9uc2UwAUKDAQoLY29tLmNoYXQudjFCDVNlcnZpY2VzUHJvdG9QAVooYXJ1a2FiZS9nZW4vY29ubmVjdC9hcnVrYS9jaGF0L3YxO2NoYXR2MaICA0NYWKoCB0NoYXQuVjHKAgdDaGF0XFYx4gITQ2hhdFxWMVxHUEJNZXRhZGF0YeoCCENoYXQ6OlYxYgZwcm90bzM", [file_chat_v1_chat_message, file_chat_v1_chat_messages, file_chat_v1_edit_chat, file_chat_v1_list_chats, file_chat_v1_new_chat]);

/**
 * @generated from service chat.v1.ChatService
 */
export const ChatService: GenService<{
  /**
   * @generated from rpc chat.v1.ChatService.ListChats
   */
  listChats: {
    methodKind: "unary";
    input: typeof ListChatsRequestSchema;
    output: typeof ListChatsResponseSchema;
  },
  /**
   * @generated from rpc chat.v1.ChatService.NewChat
   */
  newChat: {
    methodKind: "unary";
    input: typeof NewChatRequestSchema;
    output: typeof NewChatResponseSchema;
  },
  /**
   * @generated from rpc chat.v1.ChatService.EditChat
   */
  editChat: {
    methodKind: "unary";
    input: typeof EditChatRequestSchema;
    output: typeof EditChatResponseSchema;
  },
  /**
   * @generated from rpc chat.v1.ChatService.ChatMessages
   */
  chatMessages: {
    methodKind: "unary";
    input: typeof ChatMessagesRequestSchema;
    output: typeof ChatMessagesResponseSchema;
  },
  /**
   * @generated from rpc chat.v1.ChatService.ChatMessage
   */
  chatMessage: {
    methodKind: "server_streaming";
    input: typeof ChatMessageRequestSchema;
    output: typeof ChatMessageResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_chat_v1_services, 0);

