// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file provider/v1/list_providers.proto (package provider.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ModelStatus } from "../../models/v1/model_pb";
import { file_models_v1_model } from "../../models/v1/model_pb";
import type { Provider } from "../../models/v1/provider_pb";
import { file_models_v1_provider } from "../../models/v1/provider_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file provider/v1/list_providers.proto.
 */
export const file_provider_v1_list_providers: GenFile /*@__PURE__*/ = fileDesc(
  "CiBwcm92aWRlci92MS9saXN0X3Byb3ZpZGVycy5wcm90bxILcHJvdmlkZXIudjEiPgoUTGlzdFByb3ZpZGVyc1JlcXVlc3QSJgoGc3RhdHVzGAEgASgOMhYubW9kZWxzLnYxLk1vZGVsU3RhdHVzIj8KFUxpc3RQcm92aWRlcnNSZXNwb25zZRImCglwcm92aWRlcnMYASADKAsyEy5tb2RlbHMudjEuUHJvdmlkZXJCngEKD2NvbS5wcm92aWRlci52MUISTGlzdFByb3ZpZGVyc1Byb3RvUAFaKmFydWthYmUvZ2VuL2Nvbm5lY3QvcHJvdmlkZXIvdjE7cHJvdmlkZXJ2MaICA1BYWKoCC1Byb3ZpZGVyLlYxygILUHJvdmlkZXJcVjHiAhdQcm92aWRlclxWMVxHUEJNZXRhZGF0YeoCDFByb3ZpZGVyOjpWMWIGcHJvdG8z",
  [file_models_v1_model, file_models_v1_provider],
);

/**
 * @generated from message provider.v1.ListProvidersRequest
 */
export type ListProvidersRequest = Message<"provider.v1.ListProvidersRequest"> & {
  /**
   * @generated from field: models.v1.ModelStatus status = 1;
   */
  status: ModelStatus;
};

/**
 * Describes the message provider.v1.ListProvidersRequest.
 * Use `create(ListProvidersRequestSchema)` to create a new message.
 */
export const ListProvidersRequestSchema: GenMessage<ListProvidersRequest> /*@__PURE__*/ =
  messageDesc(file_provider_v1_list_providers, 0);

/**
 * @generated from message provider.v1.ListProvidersResponse
 */
export type ListProvidersResponse = Message<"provider.v1.ListProvidersResponse"> & {
  /**
   * @generated from field: repeated models.v1.Provider providers = 1;
   */
  providers: Provider[];
};

/**
 * Describes the message provider.v1.ListProvidersResponse.
 * Use `create(ListProvidersResponseSchema)` to create a new message.
 */
export const ListProvidersResponseSchema: GenMessage<ListProvidersResponse> /*@__PURE__*/ =
  messageDesc(file_provider_v1_list_providers, 1);
