// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file provider/v1/services.proto (package provider.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { ListProvidersRequestSchema, ListProvidersResponseSchema } from "./list_providers_pb";
import { file_provider_v1_list_providers } from "./list_providers_pb";
import type { UpdateProviderModelsRequestSchema, UpdateProviderModelsResponseSchema } from "./update_provider_models_pb";
import { file_provider_v1_update_provider_models } from "./update_provider_models_pb";

/**
 * Describes the file provider/v1/services.proto.
 */
export const file_provider_v1_services: GenFile = /*@__PURE__*/
  fileDesc("Chpwcm92aWRlci92MS9zZXJ2aWNlcy5wcm90bxILcHJvdmlkZXIudjEy1gEKD1Byb3ZpZGVyU2VydmljZRJWCg1MaXN0UHJvdmlkZXJzEiEucHJvdmlkZXIudjEuTGlzdFByb3ZpZGVyc1JlcXVlc3QaIi5wcm92aWRlci52MS5MaXN0UHJvdmlkZXJzUmVzcG9uc2USawoUVXBkYXRlUHJvdmlkZXJNb2RlbHMSKC5wcm92aWRlci52MS5VcGRhdGVQcm92aWRlck1vZGVsc1JlcXVlc3QaKS5wcm92aWRlci52MS5VcGRhdGVQcm92aWRlck1vZGVsc1Jlc3BvbnNlQpkBCg9jb20ucHJvdmlkZXIudjFCDVNlcnZpY2VzUHJvdG9QAVoqYXJ1a2FiZS9nZW4vY29ubmVjdC9wcm92aWRlci92MTtwcm92aWRlcnYxogIDUFhYqgILUHJvdmlkZXIuVjHKAgtQcm92aWRlclxWMeICF1Byb3ZpZGVyXFYxXEdQQk1ldGFkYXRh6gIMUHJvdmlkZXI6OlYxYgZwcm90bzM", [file_provider_v1_list_providers, file_provider_v1_update_provider_models]);

/**
 * @generated from service provider.v1.ProviderService
 */
export const ProviderService: GenService<{
  /**
   * @generated from rpc provider.v1.ProviderService.ListProviders
   */
  listProviders: {
    methodKind: "unary";
    input: typeof ListProvidersRequestSchema;
    output: typeof ListProvidersResponseSchema;
  },
  /**
   * @generated from rpc provider.v1.ProviderService.UpdateProviderModels
   */
  updateProviderModels: {
    methodKind: "unary";
    input: typeof UpdateProviderModelsRequestSchema;
    output: typeof UpdateProviderModelsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_provider_v1_services, 0);

