// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file models/v1/chat.proto (package models.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { TimeData } from "./common_pb";
import { file_models_v1_common } from "./common_pb";
import type { Model } from "./model_pb";
import { file_models_v1_model } from "./model_pb";
import type { ProviderBase } from "./provider_pb";
import { file_models_v1_provider } from "./provider_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file models/v1/chat.proto.
 */
export const file_models_v1_chat: GenFile = /*@__PURE__*/
  fileDesc("ChRtb2RlbHMvdjEvY2hhdC5wcm90bxIJbW9kZWxzLnYxIrUBCgRDaGF0EgoKAmlkGAEgASgJEg0KBXRpdGxlGAIgASgJEg4KBnByb21wdBgDIAEoCRIOCgZwaW5uZWQYBCABKAgSHwoFbW9kZWwYBSABKAsyEC5tb2RlbHMudjEuTW9kZWwSKQoIcHJvdmlkZXIYBiABKAsyFy5tb2RlbHMudjEuUHJvdmlkZXJCYXNlEiYKCXRpbWVfZGF0YRgHIAEoCzITLm1vZGVscy52MS5UaW1lRGF0YUKHAQoNY29tLm1vZGVscy52MUIJQ2hhdFByb3RvUAFaJmFydWthYmUvZ2VuL2Nvbm5lY3QvbW9kZWxzL3YxO21vZGVsc3YxogIDTVhYqgIJTW9kZWxzLlYxygIJTW9kZWxzXFYx4gIVTW9kZWxzXFYxXEdQQk1ldGFkYXRh6gIKTW9kZWxzOjpWMWIGcHJvdG8z", [file_models_v1_common, file_models_v1_model, file_models_v1_provider]);

/**
 * @generated from message models.v1.Chat
 */
export type Chat = Message<"models.v1.Chat"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string prompt = 3;
   */
  prompt: string;

  /**
   * @generated from field: bool pinned = 4;
   */
  pinned: boolean;

  /**
   * @generated from field: models.v1.Model model = 5;
   */
  model?: Model;

  /**
   * @generated from field: models.v1.ProviderBase provider = 6;
   */
  provider?: ProviderBase;

  /**
   * @generated from field: models.v1.TimeData time_data = 7;
   */
  timeData?: TimeData;
};

/**
 * Describes the message models.v1.Chat.
 * Use `create(ChatSchema)` to create a new message.
 */
export const ChatSchema: GenMessage<Chat> = /*@__PURE__*/
  messageDesc(file_models_v1_chat, 0);

