// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file models/v1/message_text_content.proto (package models.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file models/v1/message_text_content.proto.
 */
export const file_models_v1_message_text_content: GenFile = /*@__PURE__*/
  fileDesc("CiRtb2RlbHMvdjEvbWVzc2FnZV90ZXh0X2NvbnRlbnQucHJvdG8SCW1vZGVscy52MSIiChJNZXNzYWdlVGV4dENvbnRlbnQSDAoEdGV4dBgBIAEoCUKVAQoNY29tLm1vZGVscy52MUIXTWVzc2FnZVRleHRDb250ZW50UHJvdG9QAVomYXJ1a2FiZS9nZW4vY29ubmVjdC9tb2RlbHMvdjE7bW9kZWxzdjGiAgNNWFiqAglNb2RlbHMuVjHKAglNb2RlbHNcVjHiAhVNb2RlbHNcVjFcR1BCTWV0YWRhdGHqAgpNb2RlbHM6OlYxYgZwcm90bzM");

/**
 * @generated from message models.v1.MessageTextContent
 */
export type MessageTextContent = Message<"models.v1.MessageTextContent"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message models.v1.MessageTextContent.
 * Use `create(MessageTextContentSchema)` to create a new message.
 */
export const MessageTextContentSchema: GenMessage<MessageTextContent> = /*@__PURE__*/
  messageDesc(file_models_v1_message_text_content, 0);

