// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file models/v1/provider.proto (package models.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Model } from "./model_pb";
import { file_models_v1_model } from "./model_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file models/v1/provider.proto.
 */
export const file_models_v1_provider: GenFile /*@__PURE__*/ = fileDesc(
  "Chhtb2RlbHMvdjEvcHJvdmlkZXIucHJvdG8SCW1vZGVscy52MSIoCgxQcm92aWRlckJhc2USCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCSJGCghQcm92aWRlchIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEiAKBm1vZGVscxgDIAMoCzIQLm1vZGVscy52MS5Nb2RlbEKLAQoNY29tLm1vZGVscy52MUINUHJvdmlkZXJQcm90b1ABWiZhcnVrYWJlL2dlbi9jb25uZWN0L21vZGVscy92MTttb2RlbHN2MaICA01YWKoCCU1vZGVscy5WMcoCCU1vZGVsc1xWMeICFU1vZGVsc1xWMVxHUEJNZXRhZGF0YeoCCk1vZGVsczo6VjFiBnByb3RvMw",
  [file_models_v1_model],
);

/**
 * @generated from message models.v1.ProviderBase
 */
export type ProviderBase = Message<"models.v1.ProviderBase"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message models.v1.ProviderBase.
 * Use `create(ProviderBaseSchema)` to create a new message.
 */
export const ProviderBaseSchema: GenMessage<ProviderBase> /*@__PURE__*/ = messageDesc(
  file_models_v1_provider,
  0,
);

/**
 * @generated from message models.v1.Provider
 */
export type Provider = Message<"models.v1.Provider"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated models.v1.Model models = 3;
   */
  models: Model[];
};

/**
 * Describes the message models.v1.Provider.
 * Use `create(ProviderSchema)` to create a new message.
 */
export const ProviderSchema: GenMessage<Provider> /*@__PURE__*/ = messageDesc(
  file_models_v1_provider,
  1,
);
